vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        pictures:
            inject_on_load: true
            uri_prefix: /medias/pictures
            upload_destination: '%kernel.project_dir%/public/medias/pictures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer